'use strict';
(()=>{
  function updateProject(){if(!state)return;$('projectName').textContent=state.name;$('deploy').disabled=!!state.imported;$('deploy').title=state.imported?'Export this imported map to the game you choose.':'Back up and update the original Workshop game';$('saveState').textContent=state.lastSaved?'Draft saved':''}
  async function open(payload){$('openMapDialog').close();await busy('Opening your map as a separate draft…',async()=>{if(dirty)await save();let next=await api('/api/open',payload);state=next;assets=await api('/api/assets');token=assets.token;dirty=false;history=[];future=[];transaction=null;drag=null;selection=null;hover=null;lastTarget=null;customPrefabs=state.prefabs;updateProject();updateUndo();window.world3D.invalidate();window.world3D.refreshOverview();renderPalette();settings();inspect();fit();$('areaName').textContent=`Around ${state.xmax-MAP_HALF}, ${state.ymin+MAP_HALF}`;status(state.imported?'Imported draft · source file unchanged · Export to download':'Original Workshop draft opened');draw()})}
  $('openMap').onclick=async()=>{$('mapSources').replaceChildren();$('openMapDialog').showModal();try{for(let source of await api('/api/sources')){let row=document.createElement('div');row.className='map-source';let button=document.createElement('button');button.textContent=source.name;button.onclick=()=>open({source:source.id});let path=document.createElement('small');path.textContent=source.path;row.append(button,path);$('mapSources').append(row)}}catch(e){toast(e.message)}};
  $('closeOpenMap').onclick=()=>$('openMapDialog').close();
  $('importFiles').onclick=async()=>{try{let files=[...$('mapFiles').files,...$('placementFiles').files],landscapes=files.filter(f=>f.name.toLowerCase().endsWith('.orsc'));if(landscapes.length!==1)throw Error('Select exactly one Landscape.orsc file.');let map=landscapes[0];if(map.size>8000000)throw Error('That map is too large. Choose an RSC Landscape.orsc file.');let placements={},lookup={'scenerylocs.json':'objects','npclocs.json':'npcs','boundarylocs.json':'boundaries','grounditems.json':'items'};for(let file of files.filter(f=>f!==map)){let key=lookup[file.name.toLowerCase()];if(!key)throw Error('Unknown companion file: '+file.name);if(placements[key])throw Error('Choose only one '+file.name);if(file.size>16000000)throw Error('Companion file is too large: '+file.name);placements[key]=JSON.parse(await file.text())}let bytes=new Uint8Array(await map.arrayBuffer()),parts=[];for(let i=0;i<bytes.length;i+=32768)parts.push(String.fromCharCode(...bytes.subarray(i,i+32768)));await open({name:map.name,landscape:btoa(parts.join('')),placements})}catch(e){toast(e.message)}};
  $('exportMap').onclick=()=>$('exportMapDialog').showModal();$('closeExportMap').onclick=()=>$('exportMapDialog').close();
  async function download(format){$('exportMapDialog').close();await busy('Saving and exporting your world…',async()=>{if(dirty)await save();let a=document.createElement('a');a.href='/api/export?format='+format;a.download=format==='zip'?'Rsc World Editor-map-bundle.zip':'Custom_Landscape.orsc';a.click();status('Export started · original source file unchanged')})}
  $('exportBundle').onclick=()=>download('zip');$('exportLandscape').onclick=()=>download('orsc');
                                                                               
  let timer=setInterval(()=>{if(state){updateProject();clearInterval(timer)}},100);
})();
