'use strict';
window.npcCreator=(()=>{
 const dialog=document.createElement('dialog');dialog.id='npcCreator';dialog.innerHTML=`<div class="dialog-head"><h2>Create a character</h2><button id="npcClose" aria-label="Close character creator">×</button></div><p>Design a non-combat character, then write a conversation with player replies. Save to this map’s library, then place from People. Imported maps include characters in Export → complete map bundle; the original Workshop uses Save &amp; Test.</p><div class="npc-layout"><section><h3>Appearance</h3><div id="npcAppearance"></div></section><section><h3>Conversation</h3><p>Build your conversation with the quick actions below. Choose a branch to edit its spoken lines and player options.</p><div id="npcGhostspeak"></div><div id="npcPages"></div><button id="npcTry">Try conversation</button><div id="npcConversation" class="notice" hidden></div></section></div><p id="npcError" role="status"></p><button id="npcSave" class="primary">Save character to library</button>`;
 document.body.append(dialog);
 const picker=document.createElement('dialog');picker.id='npcPartPicker';picker.innerHTML='<div class="dialog-head"><h2 id="npcPartTitle">Choose a part</h2><button id="npcPartClose" aria-label="Close appearance choices">×</button></div><p>Choose a picture to try it on your character. Colours here are examples; your character keeps the colours you choose.</p><input id="npcPartSearch" type="search" aria-label="Search appearance choices" placeholder="Search styles…"><div id="npcPartCards"></div>';document.body.append(picker);
 let activePart=0;
 let catalog,draft,projectKey,previewSequence=0,previewTimer;
 function recoveryKey(){return 'rscworldeditor-npc-draft:'+projectKey+':'+(draft.id??'new')}
 function rememberDraft(){if(!draft||!dialog.open)return;try{localStorage.setItem(recoveryKey(),JSON.stringify({draft,libraryRevision:catalog.libraryRevision}));}catch(e){$('npcError').textContent='Automatic draft recovery is unavailable. Keep this window open until your character is saved.'}}
 for(const event of ['input','change','click'])dialog.addEventListener(event,rememberDraft);
 dialog.addEventListener('cancel',rememberDraft);
 function el(tag,text){let n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n}
 function field(parent,label,input){input.setAttribute('aria-label',label);let l=el('label',label);l.className='field';l.append(input);parent.append(l)}
 function button(parent,label,fn){let b=el('button',label);b.type='button';b.onclick=fn;parent.append(b);return b}
 function selectOptions(options,value,change){let input=el('select');for(let o of options){let option=el('option',o.name);option.value=o.id;input.append(option)}input.value=value;input.onchange=()=>change(+input.value);return input}
 function input(parent,label,key,max){let i=el('input');i.type='text';i.value=draft.definition[key];i.maxLength=max;i.oninput=()=>{draft.definition[key]=i.value};field(parent,label,i)}
 function preview(){clearTimeout(previewTimer);let seq=++previewSequence;previewTimer=setTimeout(async()=>{try{let r=await api('/api/npc-preview',{equipment:draft.equipment||[],definition:{...draft.definition,name:draft.definition.name||'Preview',description:draft.definition.description||'Preview'}});if(seq===previewSequence){$('npcPortrait').src=r.image;$('npcPreviewStatus').textContent='';}}catch(e){if(seq===previewSequence)$('npcPreviewStatus').textContent=e.message}},180)}
 function appearance(){const parent=$('npcAppearance');parent.replaceChildren();
  let portraitFrame=el('div');portraitFrame.className='npc-portrait-frame';portraitFrame.style.height=Math.max(192,192*(draft.definition.camera2??220)/220)+'px';let portrait=el('img');portrait.id='npcPortrait';portrait.alt='Character preview';portrait.style.width=(128*(draft.definition.camera1??145)/145)+'px';portrait.style.height=(192*(draft.definition.camera2??220)/220)+'px';portraitFrame.append(portrait);parent.append(portraitFrame);let feedback=el('p');feedback.id='npcPreviewStatus';parent.append(feedback);
  input(parent,'Name','name',40);input(parent,'Examine description','description',160);
  let sizes=el('div');sizes.className='npc-size-presets';sizes.setAttribute('role','group');sizes.setAttribute('aria-label','Body size');parent.append(el('h4','Body size'),sizes);
  for(const preset of catalog.sizes||[]){let selected=(draft.definition.camera1??145)===preset.width&&(draft.definition.camera2??220)===preset.height;let b=button(sizes,'',()=>{draft.definition.camera1=preset.width;draft.definition.camera2=preset.height;appearance()});b.className='npc-size-card'+(selected?' selected':'');b.setAttribute('aria-label',preset.name+' size');b.setAttribute('aria-pressed',String(selected));let frame=el('span');frame.className='npc-size-picture';let image=el('img');image.src='/api/placement/npcs/'+preset.npc+'.png';image.alt='';image.style.width=(52*preset.width/145)+'px';image.style.height=(80*preset.height/220)+'px';frame.append(image);b.append(frame,el('strong',preset.name));}
  let sizeNote=el('p','Changes the character’s width and height, keeping your chosen head, colours and gear.');sizeNote.className='muted';parent.append(sizeNote);
  button(parent,'Choose a starting look…',()=>choosePart(-1));
  button(parent,'Browse all '+catalog.equipment.length+' equipment items…',()=>choosePart(-2));
  let worn=el('div');worn.className='npc-worn';parent.append(worn);for(const id of draft.equipment||[]){let item=catalog.equipment.find(i=>i.id===id);if(!item)continue;let row=el('div');let img=el('img');img.src='/api/placement/items/'+id+'.png';img.alt=item.name;row.append(img,el('span',item.name+(item.appearanceID===0?' · No visible appearance':'')));button(row,'Remove',()=>{draft.equipment=draft.equipment.filter(i=>i!==id);appearance()});worn.append(row)}
  let parts=el('div');parts.className='npc-selected-parts';parent.append(parts);
  catalog.slots.forEach((slot,index)=>{let id=draft.definition['sprites'+(index+1)];let b=button(parts,'',()=>choosePart(index));b.className='npc-part-selected';b.setAttribute('aria-label','Choose '+slot.label.toLowerCase());let img=el('img');img.src='/api/npc-part/'+(index+1)+'/'+id+'.png';img.alt='';img.loading='lazy';b.append(img,el('strong',slot.label),el('span',id===-1?'None · choose':'Change style'));});
  for(let [key,label] of [['hairColour','Hair colour'],['skinColour','Skin colour'],['topColour','Shirt colour'],['bottomColour','Trouser colour']]){let i=el('input');i.type='color';i.value='#'+draft.definition[key].toString(16).padStart(6,'0');i.oninput=()=>{draft.definition[key]=parseInt(i.value.slice(1),16);preview()};field(parent,label,i)}
  let note=el('p','All wearable items are available, including items not used by existing NPCs. Equipment uses its own artwork and colours. Selecting overlapping gear replaces the previous item. Rings without wearable artwork are saved but do not change appearance.');note.className='muted';parent.append(note);preview();
 }
 function renderParts(){const parent=$('npcPartCards'),q=$('npcPartSearch').value.toLowerCase();parent.replaceChildren();
  if(activePart===-1){for(const n of catalog.templates){if(!n.name.toLowerCase().includes(q))continue;let b=button(parent,'',()=>{let name=draft.definition.name,description=draft.definition.description;draft.definition={...copy(n),name,description};picker.close();appearance()});b.className='npc-choice';let img=el('img');img.src='/api/placement/npcs/'+n.id+'.png';img.alt=n.name;img.loading='lazy';b.append(img,el('span',n.name));}return;}
  for(const item of catalog.equipment){if(activePart!==-2&&item.wearSlot!==activePart)continue;if(!(item.name+' #'+item.id).toLowerCase().includes(q))continue;let b=button(parent,'',()=>{equip(item);picker.close();appearance()});b.className='npc-choice equipment'+((draft.equipment||[]).includes(item.id)?' selected':'');b.setAttribute('aria-label','Equip '+item.name+' #'+item.id);let img=el('img');img.src='/api/placement/items/'+item.id+'.png';img.alt=item.name;img.loading='lazy';b.append(img,el('span',item.name),el('small',item.appearanceID===0?'No visible appearance':'#'+item.id));}
  if(activePart===-2)return;
  const slot=catalog.slots[activePart];
  for(const option of slot.choices){if(activePart<3&&option.id<0)continue;if(!option.name.toLowerCase().includes(q))continue;let b=button(parent,'',()=>{draft.definition['sprites'+(activePart+1)]=option.id;picker.close();appearance()});b.className='npc-choice'+(draft.definition['sprites'+(activePart+1)]===option.id?' selected':'');b.setAttribute('aria-label',option.id===-1?'No '+slot.label.toLowerCase():option.name);let img=el('img');img.src='/api/npc-part/'+(activePart+1)+'/'+option.id+'.png';img.alt=option.name;img.loading='lazy';b.append(img,el('span',option.id===-1?'None':option.name));}
 }
 function equip(item){draft.equipment=(draft.equipment||[]).filter(id=>{let old=catalog.equipment.find(i=>i.id===id);return old&&old.wearSlot!==item.wearSlot&&!(old.wearableID&item.wearableID)});draft.equipment.push(item.id)}
 function choosePart(index){activePart=index;$('npcPartTitle').textContent=index===-2?'All '+catalog.equipment.length+' equipment items':index===-1?'Choose a starting look':'Choose '+catalog.slots[index].label.toLowerCase();$('npcPartSearch').value='';renderParts();picker.showModal()}
 $('npcPartClose').onclick=()=>picker.close();$('npcPartSearch').oninput=renderParts;
 let activeNode=0,conversationMode='normal';
 function conversationNodes(){return conversationMode==='ghost'?draft.ghostNodes:draft.nodes}
 function ghostControls(){let parent=$('npcGhostspeak');parent.replaceChildren();
  let label=el('label');label.className='quest-enable';let check=el('input');check.type='checkbox';check.checked=!!draft.requiresGhostspeak;
  check.onchange=()=>{draft.requiresGhostspeak=check.checked;if(check.checked&&!draft.ghostNodes?.length)draft.ghostNodes=[{id:0,lines:[{speaker:'npc',text:'Wooo wooo wooooo!'},{speaker:'player',text:'I cannot understand this spirit. I need to wear an Amulet of Ghostspeak.'}],replies:[]}];conversationMode=check.checked?'ghost':'normal';activeNode=conversationNodes()[0].id;$('npcConversation').hidden=true;ghostControls();pages()};
  label.append(check,el('span','Different conversation without an Amulet of Ghostspeak'));parent.append(label);
  if(!draft.requiresGhostspeak)return;
  parent.append(el('p','Without the amulet equipped, only the conversation below marked “Without amulet” plays. This character’s quest dialogue and progress are blocked. Wearing it unlocks normal dialogue and quests; carrying it in a bag does not count.'));
  let tabs=el('div');tabs.className='dialogue-branches';for(const [mode,title] of [['normal','Wearing amulet: normal dialogue'],['ghost','Without amulet: blocked dialogue']]){let b=button(tabs,title,()=>{conversationMode=mode;activeNode=conversationNodes()[0].id;$('npcConversation').hidden=true;ghostControls();pages()});b.className=mode===conversationMode?'primary':'';b.setAttribute('aria-pressed',String(mode===conversationMode))}parent.append(tabs);
 }

 function nodeLines(n){if(!n.lines)n.lines=(n.text||'').split('\n').map(text=>({speaker:'npc',text}));return n.lines}
 function branchName(n){return n===conversationNodes()[0]?'Greeting':(nodeLines(n).find(l=>l.text.trim())?.text.slice(0,35)||'New response')}
 function addSpeech(speaker,greeting){let n=conversationNodes().find(n=>n.id===activeNode)||conversationNodes()[0],lines=nodeLines(n);if(lines.length>=10){$('npcError').textContent='Use up to 10 spoken lines in each branch.';return}lines[greeting?'unshift':'push']({speaker,text:''});pages()}
 function newResponse(reply){if(conversationNodes().length>=40){$('npcError').textContent='Use up to 40 conversation branches.';return}let n={id:Math.max(...conversationNodes().map(n=>n.id))+1,lines:[{speaker:'npc',text:''}],replies:[]};conversationNodes().push(n);reply.next=n.id;activeNode=n.id;pages()}
 function pages(){let parent=$('npcPages');parent.replaceChildren();let n=conversationNodes().find(n=>n.id===activeNode)||conversationNodes()[0];activeNode=n.id;
  let nav=el('div');nav.className='dialogue-branches';conversationNodes().forEach(b=>{let btn=button(nav,branchName(b),()=>{activeNode=b.id;pages()});btn.className=b===n?'primary':''});parent.append(nav);
  let card=el('div');card.className='npc-page';card.append(el('h4',n===conversationNodes()[0]?'Start the conversation':'Conversation branch'));
  let actions=el('div');actions.className='dialogue-actions';
  button(actions,'Add NPC greeting',()=>addSpeech('npc',true));button(actions,'Add player greeting',()=>addSpeech('player',true));
  let end=button(actions,'End conversation',()=>{n.ended=true;pages()});end.disabled=n.replies.length>0;end.title=end.disabled?'Remove the dialog options below to end this branch here.':'End after the last spoken line';
  let option=button(actions,'Add dialog box option',()=>{n.replies.push({text:'',next:-1});n.ended=false;pages()});option.disabled=n.replies.length>=4;
  button(actions,'Add NPC response',()=>addSpeech('npc',false));button(actions,'Add player response',()=>addSpeech('player',false));card.append(actions);
  card.append(el('p','Spoken lines play from top to bottom. Dialog box options let the player choose what to say next.'));
  let lines=nodeLines(n);lines.forEach((line,i)=>{let row=el('div');row.className='dialogue-speech '+line.speaker;row.append(el('strong',(line.speaker==='npc'?'NPC':'Player')+(i===0?' greeting':' response')));let t=el('textarea');t.rows=2;t.maxLength=500;t.value=line.text;t.placeholder=line.speaker==='npc'?'What does the NPC say?':'What does the player say?';t.oninput=()=>line.text=t.value;field(row,'Spoken line '+(i+1),t);
   let controls=el('div');if(i>0)button(controls,'Move up',()=>{[lines[i-1],lines[i]]=[lines[i],lines[i-1]];pages()});if(i<lines.length-1)button(controls,'Move down',()=>{[lines[i+1],lines[i]]=[lines[i],lines[i+1]];pages()});if(lines.length>1)button(controls,'Remove line',()=>{lines.splice(i,1);pages()});row.append(controls);card.append(row);
  });
  if(n.replies.length)card.append(el('h4','Player chooses an option'));
  n.replies.forEach((r,i)=>{let row=el('div');row.className='npc-reply';let t=el('input');t.value=r.text;t.maxLength=80;t.placeholder='Write a choice for the playerâ€¦';t.oninput=()=>r.text=t.value;field(row,'Option '+(i+1),t);field(row,'After this choice',selectOptions([{id:-1,name:'End conversation'},...conversationNodes().map(b=>({id:b.id,name:branchName(b)}))],r.next,v=>{r.next=v;pages()}));if(r.next===-1)button(row,'Write NPC response',()=>newResponse(r));else button(row,'Edit response',()=>{activeNode=r.next;pages()});button(row,'Remove option',()=>{n.replies.splice(i,1);pages()});card.append(row)});
  if(!n.replies.length){let end=el('p','Conversation ends after the last line.');end.className='notice';card.append(end)}
  if(n!==conversationNodes()[0])button(card,'Delete this branch',()=>{if(conversationNodes().some(b=>b.replies.some(r=>r.next===n.id))){$('npcError').textContent='Remove or redirect options leading to this branch before deleting it.';return}draft[conversationMode==='ghost'?'ghostNodes':'nodes']=conversationNodes().filter(b=>b!==n);activeNode=conversationNodes()[0].id;pages()});
  parent.append(card);
 }
 function tryNode(id,lineIndex=0){let parent=$('npcConversation');parent.hidden=false;parent.replaceChildren();let n=conversationNodes().find(n=>n.id===id);if(!n){parent.append(el('p','Conversation ended.'));return}let lines=nodeLines(n),line=lines[lineIndex];parent.append(el('strong',(line.speaker==='player'?'You':draft.definition.name)+':'));parent.append(el('p',line.text||'(Write this line first)'));if(lineIndex<lines.length-1){button(parent,'Continue',()=>tryNode(id,lineIndex+1));return}for(let r of n.replies)button(parent,r.text||'(Write this option first)',()=>{parent.replaceChildren();parent.append(el('strong','You:'),el('p',r.text));button(parent,'Continue',()=>tryNode(r.next))});if(!n.replies.length)parent.append(el('p','Conversation ended.'));}
 async function open(id){await busy('Opening character creator…',async()=>{catalog=await api('/api/npc-creator');projectKey=state.projectKey;let existing=catalog.custom.find(e=>e.definition.id===id);let template=catalog.templates.find(n=>n.id===11)||catalog.templates[0];draft=existing?copy(existing):{definition:{...copy(template),name:'New character',description:'A local resident.'},nodes:[{id:0,text:'Hello there!',replies:[]}]};if(existing?.baseDefinition)draft.definition=copy(existing.baseDefinition);draft.equipment=draft.equipment||[];draft.id=existing?id:null;$('npcError').textContent='';
 try{let recovered=JSON.parse(localStorage.getItem(recoveryKey())||'null');if(recovered?.draft?.nodes?.length&&recovered.draft.definition){draft=recovered.draft;catalog.libraryRevision=recovered.libraryRevision;$('npcError').textContent='Restored your unfinished character and conversation.';}}catch(e){$('npcError').textContent='Could not read the recovery copy. Your saved library is still available.';}
conversationMode='normal';if(draft.requiresGhostspeak&&!draft.ghostNodes?.length)draft.ghostNodes=[{id:0,text:'Wooo wooo wooooo!',replies:[]}];$('npcConversation').hidden=true;activeNode=draft.nodes[0].id;appearance();ghostControls();pages();dialog.showModal()})}
 $('npcClose').onclick=()=>{rememberDraft();dialog.close()};
 $('npcTry').onclick=()=>tryNode(conversationNodes()[0].id);
 $('npcSave').onclick=async()=>{let b=$('npcSave');b.disabled=true;$('npcError').textContent='Saving…';try{rememberDraft();let result=await api('/api/npc-save',{...draft,projectKey,libraryRevision:catalog.libraryRevision});try{localStorage.removeItem(recoveryKey())}catch(e){}assets=await api('/api/assets');token=assets.token;dialog.close();setTool('npcs');choice=assets.npcs.findIndex(n=>n.id===result.id);renderPalette();settings();draw();toast(result.message)}catch(e){$('npcError').textContent=e.message}finally{b.disabled=false}};
 const original=npcSettings;npcSettings=function(){let n=entries()[choice];button($('settings'),'Create a character…',()=>open());if(n?.custom)button($('settings'),'Edit this character & dialogue…',()=>open(n.id));original()};
 return {open};
})();

