'use strict';
window.objectCreator=(()=>{
 const dialog=document.createElement('dialog');dialog.id='objectCreator';dialog.innerHTML=`<div class="dialog-head"><h2 id="objectTitle">Copy & resize structure</h2><button id="objectClose" aria-label="Close structure editor">×</button></div><p>Create a scenery copy with its own name, examine text and size. Each saved copy can be placed as often as you like.</p><div class="object-layout"><section id="objectFields"></section><section><h3>Size comparison</h3><div class="object-comparison"><div><canvas id="objectOriginal" width="280" height="340" aria-label="Original structure preview"></canvas><p>Original</p></div><div><canvas id="objectPreview" width="280" height="340" aria-label="Resized structure preview"></canvas><p>Your copy</p></div></div><button id="objectRotate">Rotate preview ↻</button><p id="objectSizeSummary"></p><p class="muted">Both previews use the same scale. The model’s size and the ground space it blocks are separate settings.</p></section></div><p id="objectStatus" role="status"></p><div class="object-footer"><span id="objectSaveHint"></span><button id="objectDelete" type="button" hidden>Delete structure…</button><button id="objectSave" class="primary">Save to scenery library</button></div>`;document.body.append(dialog);
 let catalog,draft,editId,projectKey,angle=0,library,loading;
 function el(tag,text){let e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e}
 function key(){return 'rscworldeditor-object-draft:'+projectKey+':'+(editId??'copy:'+draft.sourceId)}
 function remember(){if(!draft||!dialog.open)return;try{localStorage.setItem(key(),JSON.stringify({draft,revision:catalog.revision}))}catch(e){$('objectStatus').textContent='Draft recovery is unavailable. Save your copy before closing.'}}
 for(const event of ['input','change','click'])dialog.addEventListener(event,remember);dialog.addEventListener('cancel',remember);
 async function models(){if(!loading)loading=api('/models3d.json').then(v=>library=v).catch(e=>{loading=null;throw e});return loading}
 function mesh(source){return library?.models[library.mapping[source]]}
 function color(value){if(value<0){let n=-1-value;return `rgb(${(n>>10&31)*8},${(n>>5&31)*8},${(n&31)*8})`}return '#879f75'}
 function points(model,size,direction){let a=direction*Math.PI/4,c=Math.cos(a),s=Math.sin(a);return model.v.map(v=>v.map((n,i)=>Math.round(n*size[i]/100))).map(([x,y,z])=>[x*c+z*s,y,z*c-x*s])}
 function projected(model,size,direction){return points(model,size,direction).map(([x,y,z])=>[x-z*.5,y+(x+z)*.25,x+z-y*.2])}
 function bounds(v){return {minX:Math.min(...v.map(p=>p[0])),maxX:Math.max(...v.map(p=>p[0])),minY:Math.min(...v.map(p=>p[1])),maxY:Math.max(...v.map(p=>p[1]))}}
 function render(canvas,model,size,direction,sharedBounds){let g=canvas.getContext('2d');g.clearRect(0,0,canvas.width,canvas.height);if(!model){g.fillStyle='#ccd9d8';g.fillText('Model unavailable',15,35);return}let v=projected(model,size,direction),b=sharedBounds||bounds(v),factor=Math.min((canvas.width-28)/Math.max(1,b.maxX-b.minX),(canvas.height-34)/Math.max(1,b.maxY-b.minY)),cx=canvas.width/2-(b.minX+b.maxX)/2*factor,cy=canvas.height-18-b.maxY*factor;
  const faces=model.f.slice().sort((a,b)=>a[1].reduce((sum,i)=>sum+v[i][2],0)/a[1].length-b[1].reduce((sum,i)=>sum+v[i][2],0)/b[1].length);
  for(const [paint,indices] of faces){if(paint===12345678)continue;g.beginPath();indices.forEach((id,i)=>{let p=v[id];g[i?'lineTo':'moveTo'](cx+p[0]*factor,cy+p[1]*factor)});g.closePath();g.fillStyle=color(paint);g.fill();g.strokeStyle='#10222a44';g.lineWidth=.5;g.stroke()}
 }
 function redraw(){let model=mesh(draft.sourceId),both=model?[...projected(model,[100,100,100],angle),...projected(model,draft.scale,angle)]:null,b=both?bounds(both):null;render($('objectOriginal'),model,[100,100,100],angle,b);render($('objectPreview'),model,draft.scale,angle,b);$('objectSizeSummary').textContent=`Model: ${draft.scale[0]}% wide × ${draft.scale[1]}% tall × ${draft.scale[2]}% deep. Ground space: ${draft.width} × ${draft.height} tiles.`}
 function field(parent,label,input){let l=el('label',label);l.className='field';input.setAttribute('aria-label',label);l.append(input);parent.append(l)}
 function number(parent,label,value,min,max,fn){let input=el('input');input.type='number';input.min=min;input.max=max;input.step=1;input.value=value;input.oninput=()=>{let v=Number(input.value);if(!Number.isInteger(v)||v<min||v>max){input.setCustomValidity(`Use ${min} to ${max}.`);return}input.setCustomValidity('');fn(v);redraw()};field(parent,label,input);return input}
 function fields(){let parent=$('objectFields');parent.replaceChildren();let source=catalog.objects[draft.sourceId];parent.append(el('p','Copied from '+(source.gameName||source.name)+' · #'+source.id));
  for(const [key,label,max,tag] of [['name','Name',60,'input'],['description','Examine text',500,'textarea']]){let i=el(tag);i.value=draft[key];i.maxLength=max;i.required=true;i.oninput=()=>draft[key]=i.value;field(parent,label,i)}
  let overall=el('input');overall.type='range';overall.min=10;overall.max=400;overall.step=5;overall.value=draft.scale[1];overall.oninput=()=>{draft.scale=[+overall.value,+overall.value,+overall.value];for(let i=0;i<3;i++)axes[i].value=draft.scale[i];redraw()};field(parent,'Overall size (100% = original)',overall);
  let dimensions=el('div');dimensions.className='object-axis';let axes=['Width %','Height %','Depth %'].map((label,i)=>number(dimensions,label,draft.scale[i],10,400,v=>draft.scale[i]=v));parent.append(dimensions);
  parent.append(el('h3','Ground space'));let footprint=el('div');footprint.className='object-axis';number(footprint,'Width in tiles',draft.width,1,16,v=>draft.width=v);number(footprint,'Depth in tiles',draft.height,1,16,v=>draft.height=v);parent.append(footprint);
  for(const [key,label] of [['solid','Blocks walking through its ground space'],['chop','Keep the original tree’s chopping and logs']]){if(key==='chop'&&!source.canChop)continue;let check=el('input');check.type='checkbox';check.checked=draft[key];check.onchange=()=>draft[key]=check.checked;let l=el('label');l.className='quest-enable';l.append(check,el('span',label));parent.append(l)}
  parent.append(el('p',source.canChop?'Chopping uses the original level requirement, logs, experience and respawn time.':'This copy is scenery with Examine. Special actions such as doors, ladders and quest scripts are not copied.'));
 }
 async function open(id,makeCopy=false){await busy('Opening structure editor…',async()=>{catalog=await api('/api/object-creator');await models();projectKey=state.projectKey;let source=catalog.objects[id];if(!source||source.deleted)throw Error('Choose scenery to copy first.');let existing=catalog.custom.find(r=>r.id===id);editId=existing&&!makeCopy?id:null;
  draft=existing?copy(existing):{sourceId:id,name:source.gameName||source.name,description:source.description,scale:[100,100,100],width:source.width,height:source.height,solid:source.solid,chop:!!source.canChop};if(makeCopy)draft.name+=' copy';delete draft.id;angle=0;$('objectStatus').textContent='';
  try{let restored=JSON.parse(localStorage.getItem(key())||'null');if(restored?.draft?.sourceId===draft.sourceId){draft=restored.draft;catalog.revision=restored.revision;$('objectStatus').textContent='Restored your unfinished scenery copy.'}}catch(e){}
  $('objectDelete').hidden=editId===null;$('objectTitle').textContent=editId===null?'Copy & resize structure':'Edit custom structure';$('objectSaveHint').textContent=editId===null?'The original stays unchanged.':'Updates every placement of this custom object.';fields();redraw();dialog.showModal();
 })}
 $('objectClose').onclick=()=>{remember();dialog.close()};$('objectRotate').onclick=()=>{angle=(angle+1)%8;redraw()};
 $('objectSave').onclick=async()=>{for(const input of dialog.querySelectorAll('input,textarea'))if(!input.reportValidity())return;let b=$('objectSave');b.disabled=true;$('objectStatus').textContent='Saving…';try{remember();let result=await api('/api/object-save',{id:editId,object:draft,projectKey,revision:catalog.revision});try{localStorage.removeItem(key())}catch(e){}assets=await api('/api/assets');token=assets.token;dialog.close();setTool('objects');choice=assets.objects.findIndex(o=>o.id===result.id);$('search').value=draft.name;dirty=true;updateUndo();window.world3D?.invalidate();renderPalette();settings();draw();toast(result.message)}catch(e){$('objectStatus').textContent=e.message}finally{b.disabled=false}};
 async function removeStructure(id){
  if(!confirm('Are you sure you want to delete this structure?\n\nThis removes it from your scenery library, all placements on this map, and saved stamps. Current map edits will be saved first and undo history cleared. A backup will be kept.'))return;
  await busy('Deleting structure…',async()=>{
   const expectedProject=state.projectKey;
   const current=dialog.open?catalog:await api('/api/object-creator');
   if(dirty)await save();
   let result=await api('/api/object-delete',{id,confirmed:true,projectKey:expectedProject,revision:current.revision,mapRevision:state.revision});
   try{localStorage.removeItem('rscworldeditor-object-draft:'+expectedProject+':'+id)}catch(e){}
   dialog.close();assets=await api('/api/assets');token=assets.token;state=await api(`/api/region?xmax=${state.xmax}&ymin=${state.ymin}`);
   history=[];future=[];transaction=null;clipboard=null;selection=null;hover=null;customPrefabs=state.prefabs;dirty=true;setTool('objects');choice=0;$('search').value='';updateUndo();window.world3D?.invalidate();renderPalette();settings();inspect();draw();toast(result.message);
  });
 }
 $('objectDelete').onclick=()=>removeStructure(editId);
 const originalSettings=modelSettings;modelSettings=function(){let entry=entries()[choice];if(entry){let b=el('button','Copy & resize structure…');b.className='wide';b.onclick=()=>open(entry.id,true);$('settings').append(b);if(entry.custom){let e=el('button','Edit this custom structure…');e.className='wide';e.onclick=()=>open(entry.id);$('settings').append(e);let remove=el('button','Delete this structure…');remove.className='wide';remove.onclick=()=>removeStructure(entry.id);$('settings').append(remove)}}originalSettings()};
 const originalCard=paintModelCard;paintModelCard=function(canvas,id,direction){let entry=assets.objects[id];if(!entry?.custom)return originalCard(canvas,id,direction);if(!library){models().then(()=>{if(canvas.isConnected)paintModelCard(canvas,id,direction)}).catch(()=>{});return}render(canvas,mesh(entry.sourceId),entry.scale,direction)};
 function drawMap(id,direction,x,y,w,h,ghost){let entry=assets.objects[id],model=mesh(entry.sourceId);if(!model){models().then(draw).catch(()=>{});return false}let vertices=points(model,entry.scale,direction);ctx.save();if(ghost)ctx.globalAlpha=.65;let faces=model.f.slice().sort((a,b)=>b[1].reduce((sum,i)=>sum+vertices[i][1],0)/b[1].length-a[1].reduce((sum,i)=>sum+vertices[i][1],0)/a[1].length);for(const [paint,indices] of faces){if(paint===12345678)continue;ctx.beginPath();indices.forEach((id,i)=>{let v=vertices[id];ctx[i?'lineTo':'moveTo'](x+w/2-v[0]/128,y+h/2+v[2]/128)});ctx.closePath();ctx.fillStyle=color(paint);ctx.fill();ctx.strokeStyle='#10222a66';ctx.lineWidth=1/scale;ctx.stroke()}ctx.restore();return true}
 return {open,drawMap};
})();
