'use strict';
window.questEditor=(()=>{
 const $q=id=>document.getElementById(id),el=(tag,text)=>{let n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
 const d=el('dialog');d.id='questEditor';document.body.append(d);
 const picker=el('dialog');picker.id='questPicker';document.body.append(picker);
 let catalog,draft,projectKey,tab=0,timer,previewStage=0,previewHas=false,previewDone=new Set(),saving=false;
 const clone=v=>JSON.parse(JSON.stringify(v));
 function button(p,label,fn,cls=''){let b=el('button',label);b.type='button';b.className=cls;b.onclick=fn;p.append(b);return b}
 function field(p,label,value,change,{multi=false,number=false,max=500}={}){let l=el('label');l.className='field';l.append(el('span',label));let i=el(multi?'textarea':'input');if(!multi)i.type=number?'number':'text';else i.rows=3;i.value=value??'';if(number){i.min=0;i.max=10000000}else i.maxLength=max;i.oninput=()=>{change(number?Number(i.value):i.value);remember()};l.append(i);p.append(l);return i}
 function choose(p,label,options,value,fn){let l=el('label');l.className='field';l.append(el('span',label));let s=el('select');for(let [id,name] of options){let o=el('option',name);o.value=id;s.append(o)}s.value=value;s.onchange=()=>{fn(s.value);remember();render()};l.append(s);p.append(l);return s}
 function name(kind,id){let v=catalog[kind].find(v=>v.id===id);return kind==='npcs'?(v?.gameName||v?.name||'Choose an NPC'):(v?.name||'Choose an item')}
 function card(p,kind,id,label,change,locked=false){let b=button(p,'',()=>pick(kind,change));b.className='quest-asset';b.disabled=locked;let img=el('img');img.src='/api/placement/'+kind+'/'+id+'.png';img.alt='';if(id>=0)b.append(img);let words=el('span');words.append(el('small',label),el('strong',name(kind,id)),el('small',locked?'Published quest':(kind==='npcs'?'Click to choose an NPC':'Click to choose a picture')));b.append(words);return b}
 function pick(kind,change){picker.replaceChildren();let head=el('div');head.className='dialog-head';head.append(el('h2',kind==='npcs'?'Choose a character':'Choose an item'));button(head,'Close',()=>picker.close());picker.append(head);let search=el('input');search.type='search';search.placeholder='Search by name…';search.setAttribute('aria-label','Search quest pictures');picker.append(search);let cards=el('div');cards.className='quest-pictures';picker.append(cards);let limit=80;
  function draw(){cards.replaceChildren();let rows=catalog[kind].filter(v=>(v.gameName||v.name).toLowerCase().includes(search.value.toLowerCase()));rows.slice(0,limit).forEach(v=>{let b=button(cards,'',()=>{change(v.id);remember();picker.close();render()});let img=el('img');img.loading='lazy';img.src='/api/placement/'+kind+'/'+v.id+'.png';img.alt='';b.append(img,el('span',name(kind,v.id)))});if(rows.length>limit)button(cards,'Show more',()=>{limit+=80;draw()})}search.oninput=()=>{limit=80;draw()};draw();picker.showModal();search.focus();
 }
 const talkDialog=el('dialog');talkDialog.id='questConversation';document.body.append(talkDialog);
 const uid=()=> 'part_'+Math.random().toString(36).slice(2,12);
 function legacyConversation(text,reply,action){let first={id:uid(),title:'Opening',lines:(text||'').split('\n').filter(x=>x.trim()).map(text=>({speaker:'npc',text})),choices:[],ending:'end'},nodes=[first];if(action!=='end'){let yes={id:uid(),title:action==='start'?'Accept the quest':'Finish this step',lines:[],choices:[],ending:action},no={id:uid(),title:'Maybe later',lines:[],choices:[],ending:'end'};first.choices=[{text:reply||(action==='start'?'Yes, I will help.':'Continue'),next:yes.id},{text:'Not right now',next:no.id}];nodes.push(yes,no)}return {entry:first.id,nodes}}
 function conversationButton(parent,owner,key,title,npc,action,oldText,oldReply){
  let box=el('div');box.className='quest-conversation-summary';box.append(el('h4',title),el('p','Add NPC speech, player speech, chat box messages and reply choices.'));
  let c=owner[key];box.append(el('small',c?c.nodes.reduce((a,n)=>a+n.lines.length,0)+' speech cards · '+c.nodes.reduce((a,n)=>a+n.choices.length,0)+' reply choices':''));
  button(box,'Edit '+title.toLowerCase(),()=>{if(!owner[key])owner[key]=legacyConversation(oldText,oldReply,action);remember();editConversation(owner[key],npc,action,title)});parent.append(box);
 }
 function editConversation(c,npc,action,title){
  let current=c.entry;const actionName=action==='start'?'Start quest':action==='advance'?'Complete this step':'End conversation';
  function redraw(){
   talkDialog.replaceChildren();let h=el('div');h.className='dialog-head';h.append(el('h2',title));button(h,'Done',async()=>{await storeDraft();talkDialog.close();render()});talkDialog.append(h);
   let body=el('div');body.className='quest-talk-body';talkDialog.append(body);
   body.append(el('p','Read from top to bottom. Reply choices lead to another conversation part. The selected reply is spoken by the player automatically.'));
   function select(parent,label,options,value,change){let l=el('label');l.className='field';l.append(el('span',label));let s=el('select');options.forEach(([id,t])=>{let o=el('option',t);o.value=id;s.append(o)});s.value=value;s.onchange=()=>{change(s.value);remember();redraw()};l.append(s);parent.append(l);return s;}
   select(body,'Conversation part',c.nodes.map(n=>[n.id,(n.id===c.entry?'Opening · ':'')+n.title]),current,v=>current=v);
   let part=c.nodes.find(n=>n.id===current);field(body,'Name of this part (only seen in the editor)',part.title,v=>part.title=v,{max:80});
   if(current!==c.entry){button(body,'Back to opening',()=>{current=c.entry;redraw()});if(!c.nodes.some(n=>n.ending===current||n.choices.some(x=>x.next===current)))button(body,'Remove unused part',()=>{c.nodes=c.nodes.filter(n=>n.id!==current);current=c.entry;remember();redraw()})}
   part.lines.forEach((line,i)=>{let box=el('div');box.className='quest-speech-card '+line.speaker;box.append(el('strong',(i+1)+'. '+(line.speaker==='npc'?name('npcs',npc):line.speaker==='player'?'Player':'Chat box')));
    select(box,'Speaker',[['npc',name('npcs',npc)],['player','Player'],['chat','Chat box message']],line.speaker,v=>line.speaker=v);
    field(box,line.speaker==='chat'?'Message (for example: Sack: Mumblemumble)':'What do they say?',line.text,v=>line.text=v,{multi:true,max:2000});
    let controls=el('div');controls.className='quest-talk-actions';if(i>0)button(controls,'Move up',()=>{[part.lines[i-1],part.lines[i]]=[line,part.lines[i-1]];remember();redraw()});if(i<part.lines.length-1)button(controls,'Move down',()=>{[part.lines[i+1],part.lines[i]]=[line,part.lines[i+1]];remember();redraw()});button(controls,'Remove line',()=>{part.lines.splice(i,1);remember();redraw()});box.append(controls);body.append(box);
   });
   let add=el('div');add.className='quest-talk-actions';[['npc','+ NPC speech'],['player','+ Player speech'],['chat','+ Chat box message']].forEach(([speaker,label])=>button(add,label,()=>{if(part.lines.length>=80)return;part.lines.push({speaker,text:''});remember();redraw();let fields=talkDialog.querySelectorAll('textarea');fields[fields.length-1]?.focus()}));body.append(add);
   let paste=el('details');paste.append(el('summary','Paste several lines at once'));paste.append(el('p','Use one line per speech: NPC: Hello, Player: Who are you?, or Chat: Sack: Mumblemumble. Any other speaker name becomes a chat box message. Pasted lines are added to this part.'));let input=el('textarea');input.rows=5;input.placeholder='NPC: Can I help you?\nPlayer: Who are you?\nChat: Sack: Mumblemumble';input.setAttribute('aria-label','Conversation to paste');paste.append(input);button(paste,'Add pasted lines',()=>{let lines=input.value.split('\n').map(x=>x.trim().replace(/^[-•]\s*/, '').replace(/\*\*/g,'')).filter(Boolean);if(lines.length+part.lines.length>80){error.textContent='Please keep each part to 80 speech cards or fewer.';return}for(let text of lines){let m=text.match(/^([^:]+):\s*(.*)$/);let who=m?.[1].trim().toLowerCase();let speaker=who==='player'?'player':who==='npc'||who===name('npcs',npc).toLowerCase()?'npc':'chat';part.lines.push({speaker,text:m&&(['player','npc','chat'].includes(who)||speaker==='npc')?m[2]:text})}remember();redraw()});body.append(paste);
   body.append(el('h3','What happens after these lines?'));
   if(part.choices.length){body.append(el('p','Show the player these reply choices:'));part.choices.forEach((choice,i)=>{let row=el('div');row.className='quest-choice-card';field(row,'Reply option '+(i+1),choice.text,v=>choice.text=v,{max:80});select(row,'Then go to',c.nodes.map(n=>[n.id,n.title]),choice.next,v=>choice.next=v);button(row,'Write what happens next',()=>{current=choice.next;redraw()});button(row,'Remove option',()=>{part.choices.splice(i,1);remember();redraw()});body.append(row)})}
   else select(body,'After the final line',[['end','End conversation'],...(action==='end'?[]:[[action,actionName]]),...c.nodes.filter(n=>n.id!==part.id).map(n=>[n.id,'Continue to: '+n.title])],part.ending,v=>part.ending=v);
   if(part.choices.length<4&&c.nodes.length<60)button(body,'+ Add player reply choice',()=>{let next={id:uid(),title:'Reply '+(c.nodes.length),lines:[],choices:[],ending:'end'};c.nodes.push(next);part.choices.push({text:'',next:next.id});remember();redraw()});
   body.append(el('small',action==='end'?'Completion conversations do not give rewards again.':'Progress changes only when a conversation part ends with “'+actionName+'”. Ending a conversation leaves progress unchanged.'));
   let error=el('p');error.setAttribute('role','status');body.append(error);
   button(body,'Preview from opening',()=>{let preview=el('div');preview.className='quest-step';body.append(preview);playConversation(preview,c,npc,a=>preview.append(el('strong',a==='end'?'Conversation ended.':actionName+' (preview only).')))});
  }
  redraw();talkDialog.showModal();
 }
 talkDialog.addEventListener('cancel',()=>{storeDraft();render()});
 function playConversation(container,c,npc,done){let visits=0;function show(id,reply){if(++visits>200){container.append(el('p','Preview stopped: conversation loop.'));return}let part=c.nodes.find(n=>n.id===id);if(!part){container.append(el('p','Choose a valid conversation destination.'));return}container.replaceChildren(el('h4',part.title));if(reply)container.append(el('p','Player: '+reply));for(let line of part.lines){let row=el('p');row.style.whiteSpace='pre-wrap';row.append(el('strong',(line.speaker==='npc'?name('npcs',npc):line.speaker==='player'?'Player':'Chat box')+': '),document.createTextNode(line.text));container.append(row)}if(part.choices.length){container.append(el('p','Choose a reply:'));for(let choice of part.choices)button(container,choice.text||'(Write this reply)',()=>show(choice.next,choice.text))}else button(container,'Continue',()=>{if(c.nodes.some(n=>n.id===part.ending))show(part.ending);else{container.replaceChildren();done(part.ending)}})}show(c.entry)}

 const skillNames=['Attack','Defence','Strength','Hits','Ranged','Prayer','Magic','Cooking','Woodcutting','Fletching','Fishing','Firemaking','Crafting','Smithing','Mining','Herblaw','Agility','Thieving'];
 function normalizeQuest(){draft.requirements??=[];draft.guide??={};draft.reward.experience??=draft.reward.xp>0?[{skill:draft.reward.skill,xp:draft.reward.xp}]:[];draft.steps.forEach(s=>s.guide??={});}
 function skillRows(parent,rows,key,maximum,addLabel){
  if(!rows.length)parent.append(el('p',key==='xp'?'No skill XP rewards yet.':'No skill level requirements.'));
  rows.forEach((r,i)=>{let box=el('div');box.className='quest-step';choose(box,'Skill',skillNames.map((name,id)=>[id,name]).filter(([id])=>id===r.skill||!rows.some(v=>v.skill===id)),r.skill,v=>r.skill=+v);let input=field(box,key==='xp'?'XP awarded':'Required base level',r[key],v=>r[key]=v,{number:true});input.min=1;input.max=maximum;button(box,'Remove '+(key==='xp'?'XP reward':'requirement'),()=>{rows.splice(i,1);remember();render()});parent.append(box)});
  if(rows.length<18)button(parent,'+ '+addLabel,()=>{rows.push({skill:skillNames.findIndex((n,i)=>!rows.some(r=>r.skill===i)),[key]:key==='xp'?500:1});remember();render()});
 }
 function guideEditor(body){
  body.append(el('h3','Write your in-game quest guide'),el('p',"This text appears when a player clicks your quest in the quest list. Leave a field blank to use the automatic suggestion."));
  function section(owner,title,defaults){let box=el('div');box.className='quest-step';box.append(el('h4',title));for(let [key,label] of [['next','What should the player do?'],['where','Where should they go?'],['bring','What should they bring?']]){let input=field(box,label,owner.guide[key],v=>owner.guide[key]=v,{multi:true,max:1000});input.placeholder=defaults[key]||'Leave blank for the automatic guide';}body.append(box);}
  section(draft,'Before starting',{next:'Speak to '+name('npcs',draft.giver)+' to begin this quest.',where:(!draft.location&&name('npcs',draft.giver)==='Bear')?'Speak to Bear south east of Varrock':(draft.location?draft.location+'. ':'')+'Speak to '+name('npcs',draft.giver)+'.',bring:"Raw beef"});
  draft.steps.forEach((s,i)=>section(s,'Step '+(i+1)+' · '+s.objective,{next:s.objective,where:(s.location||draft.location||'')+' · Speak to '+name('npcs',s.npc)+'.',bring:['bring','check'].includes(s.kind)?s.amount+' × '+name('items',s.item)+'; automatically shows how many the player has.':'Automatic task information.'}));
  field(body,'Guide text after completing the quest',draft.guide.complete,v=>draft.guide.complete=v,{multi:true,max:1000}).placeholder='You have completed '+(draft.name||'this quest')+'.';
  
 }
 function fresh(){return {name:'',giver:11,intro:'Could you help me with something?',accept:'I would be happy to help.',finish:'Thank you for your help!',enabled:false,steps:[step()],reward:{coins:0,item:-1,amount:1,xp:0,skill:0}}}
 function step(){return {kind:'talk',npc:11,objective:"Speak to the next NPC.",speech:'Thank you for coming.',reply:'I understand.',reminder:'Please finish the current task first.',item:10,amount:1}}
 function remember(){if(!draft)return;clearTimeout(timer);timer=setTimeout(()=>storeDraft(),350)}
 async function storeDraft(){try{await api('/api/quest-draft',{projectKey,quest:draft});let n=$q('questRecovery');if(n)n.textContent='Unfinished edits saved for recovery.'}catch(e){let n=$q('questRecovery');if(n)n.textContent='Recovery could not save: '+e.message}}
 async function open(){await busy('Opening quests…',async()=>{catalog=await api('/api/quests');if(!catalog.questOptionsVersion)throw Error('The quest guide and rewards update needs a Rsc World Editor restart. Close Rsc World Editor and reopen it using your usual batch file. Your saved quest recovery will still be there.');projectKey=state.projectKey;draft=null;tab=0;render();d.showModal()})}
 function edit(q){draft=clone(q);let r=catalog.drafts?.[draft.id||'new'];if(r)draft=clone(r);tab=0;render()}
 function render(){d.replaceChildren();let h=el('div');h.className='dialog-head';h.append(el('h2','Quest Builder'));button(h,'Close',async()=>{if(draft)await storeDraft();d.close()});d.append(h);
  if(!draft){d.append(el('p',"Build your very own quest! And yes, you can make a sequel to Cook's Assistant. Who am I to judge?"));button(d,'Create a quest',()=>edit(fresh()),'primary');for(let q of catalog.quests){let row=el('div');row.className='quest-library-row';row.append(el('strong',q.name),el('span',q.enabled?'Ready for players':'Draft · not in game'));button(row,'Edit quest',()=>edit(q));button(row,'Duplicate',()=>{let copy=clone(q);delete copy.id;delete copy.published;copy.enabled=false;copy.name+=' (copy)';draft=copy;tab=0;render()});d.append(row)}if(catalog.drafts?.new)button(d,'Resume unfinished quest',()=>edit(fresh()));return;}
  normalizeQuest();let top=el('div');top.className='quest-tabs';['1 · Story','2 · Quest steps','3 · Rewards','4 · Guide','5 · Try & save'].forEach((label,i)=>button(top,label,()=>{tab=i;render()},i===tab?'primary':''));d.append(top);
  let body=el('section');body.className='quest-body';d.append(body);let locked=!!draft.published;
  if(tab===0){field(body,'Quest name',draft.name,v=>draft.name=v,{max:60});card(body,'npcs',draft.giver,'Quest giver',v=>draft.giver=v,locked);field(body,'Quest area name (optional)',draft.location,v=>draft.location=v,{max:120});body.append(el('p',"The area name will appear in the in-game quest guide. Create a new NPC if you'd like only one particular person to offer the quest."));conversationButton(body,draft,'conversation','Opening conversation',draft.giver,'start',draft.intro,draft.accept);body.append(el('h3','Skill levels needed to start'));body.append(el('p','Quests work with your base skill levels, not level boosters. These requirements are checked before starting a quest.'));skillRows(body,draft.requirements,'level',99,'Add level requirement');}
  if(tab===1){body.append(el('h3','What does the player do?'));if(locked)body.append(el('p','This quest has been enabled. Dialogue can be edited; duplicate the quest to change its steps without changing existing player progress.'));
   draft.steps.forEach((s,index)=>{let box=el('div');box.className='quest-step';box.append(el('h4','Step '+(index+1)));let type=choose(box,'Task', [['talk','Talk to someone'],['bring','Bring an item · hand it over'],['check','Show an item · keep it'],['give','Receive an item']],s.kind,v=>s.kind=v);type.disabled=locked;card(box,'npcs',s.npc,'Character for this step',v=>s.npc=v,locked);field(box,'Objective shown to the player',s.objective,v=>s.objective=v,{max:160});field(box,"Step area name (optional)",s.location,v=>s.location=v,{max:120});
    if(s.kind!=='talk'){card(box,'items',s.item,'Quest item',v=>s.item=v,locked);field(box,'Quantity',s.amount,v=>s.amount=v,{number:true}).disabled=locked;}
    if(index>0&&s.kind==='bring'&&draft.steps[index-1].kind==='bring'&&s.npc===draft.steps[index-1].npc){let label=el('label');label.className='quest-enable';let check=el('input');check.type='checkbox';check.checked=!!s.anyOrderWithPrevious;check.onchange=()=>{s.anyOrderWithPrevious=check.checked;remember();render()};label.append(check,el('span','Accept together with the previous delivery, in any order'));box.append(label,el('p','The character accepts any outstanding item in this group. All must be delivered before later tasks unlock. Each item uses its own step conversation; put final thanks in the completion conversation.'));}else s.anyOrderWithPrevious=false;
    conversationButton(box,s,'conversation','Step conversation',s.npc,'advance',s.speech,s.reply);field(box,'Reminder if the player is not ready',s.reminder,v=>s.reminder=v,{multi:true});
    if(!locked){if(index>0)button(box,'Move up',()=>{[draft.steps[index-1],draft.steps[index]]=[s,draft.steps[index-1]];remember();render()});if(draft.steps.length>1)button(box,'Remove step',()=>{draft.steps.splice(index,1);remember();render()})}body.append(box);
   });if(!locked&&draft.steps.length<20)button(body,'+ Add another step',()=>{draft.steps.push(step());remember();render()});}
  if(tab===2){body.append(el('h3',"Quest reward(s)"));body.append(el('p',"Rewards are given once. You can't be greedy! If your inventory is full, the player can go bank and return to the final NPC."));field(body,'Coins (0 for none)',draft.reward.coins,v=>draft.reward.coins=v,{number:true});card(body,'items',draft.reward.item,'Optional reward item',v=>{draft.reward.item=v;draft.reward.amount=1});if(draft.reward.item>=0){field(body,'Reward item quantity',draft.reward.amount,v=>draft.reward.amount=v,{number:true});button(body,'No item reward',()=>{draft.reward.item=-1;remember();render()})}
   body.append(el('h3','Skill experience rewards'));skillRows(body,draft.reward.experience,'xp',10000000,'Add XP reward');body.append(el('small',"Custom quests do not add official quest points."));conversationButton(body,draft,'finishConversation','Completion conversation',draft.giver,'end',draft.finish,'');}
  if(tab===3){guideEditor(body);}
  if(tab===4){body.append(el('h3',draft.name||'Your quest'));body.append(el('p','Click the button below to try your quest.'));button(body,'Try the quest',()=>{previewStage=0;previewHas=false;previewDone=new Set();simulate()});let preview=el('div');preview.id='questSimulation';body.append(preview);let label=el('label');label.className='quest-enable';let check=el('input');check.type='checkbox';check.checked=draft.enabled;check.onchange=()=>{draft.enabled=check.checked;remember()};label.append(check,el('span','Enable this quest for players'));body.append(label,el('p',"Make sure before you save your quest that you've set everything up correctly or it might not work the way you'd like it to. Go back and check first otherwise you can edit it later."));
   button(body,'Save quest',async()=>{if(saving)return;saving=true;clearTimeout(timer);await storeDraft();try{let r=await api('/api/quest-save',{projectKey,revision:catalog.revision,quest:draft});catalog=await api('/api/quests');draft=clone(r.quest);render();$q('questStatus').textContent=r.message}catch(e){$q('questStatus').textContent=e.message}finally{saving=false}},'primary');}
  let foot=el('div');foot.className='quest-footer';button(foot,'Quest library',async()=>{await storeDraft();catalog=await api('/api/quests');draft=null;render()});if(tab>0)button(foot,'Back',()=>{tab--;render()});if(tab<4)button(foot,'Next',()=>{tab++;render()},'primary');d.append(foot);let status=el('p');status.id='questStatus';status.setAttribute('role','status');d.append(status);let recovery=el('small','Edits are saved for recovery as you work.');recovery.id='questRecovery';d.append(recovery);
 }
 function simulate(){let p=$q('questSimulation');p.replaceChildren();p.className='quest-step';if(previewStage===0){if(draft.conversation){playConversation(p,draft.conversation,draft.giver,a=>{if(a==='start'){previewStage=1;simulate()}else p.append(el('p','Quest not started.'))});return}p.append(el('strong',name('npcs',draft.giver)),el('p',draft.intro));button(p,draft.accept,()=>{previewStage=1;simulate()});button(p,'Not right now',()=>p.replaceChildren(el('p','Quest not started. Try again whenever you like.')));return}if(previewStage>draft.steps.length){if(draft.finishConversation){playConversation(p,draft.finishConversation,draft.giver,()=>p.append(el('strong',"Quest Complete!")));return}p.append(el('strong',"Quest Complete!"),el('p',draft.finish));return}let start=previewStage-1,end=start;while(end+1<draft.steps.length&&draft.steps[end+1].anyOrderWithPrevious&&draft.steps[end+1].kind==='bring'&&draft.steps[end+1].npc===draft.steps[start].npc)end++;if(end>start){p.append(el('p','These deliveries can be made in any order. Choose an item to pretend you have:'));for(let i=start;i<=end;i++){if(previewDone.has(i))continue;let delivery=draft.steps[i];button(p,delivery.amount+' × '+name('items',delivery.item),()=>{let advance=()=>{previewDone.add(i);while(previewDone.has(previewStage-1))previewStage++;simulate()};if(delivery.conversation)playConversation(p,delivery.conversation,delivery.npc,a=>{if(a==='advance')advance();else simulate()});else{p.replaceChildren(el('p',delivery.speech));button(p,delivery.reply,advance)}})}return;}let s=draft.steps[previewStage-1];p.append(el('strong','Step '+previewStage+': '+(s.objective==='Speak to the next character.'?'Speak to the next NPC.':s.objective)));if(s.kind==='bring'||s.kind==='check'){let label=el('label');let cb=el('input');cb.type='checkbox';cb.checked=previewHas;cb.onchange=()=>{previewHas=cb.checked;simulate()};label.append(cb,el('span','Pretend I have '+s.amount+' × '+name('items',s.item)));p.append(label);if(!previewHas){p.append(el('p',s.reminder));return}}if(s.conversation){let conversation=el('div');p.append(conversation);playConversation(conversation,s.conversation,s.npc,a=>{if(a==='advance'){previewDone.add(previewStage-1);previewStage++;while(previewDone.has(previewStage-1))previewStage++;previewHas=false;simulate()}else conversation.append(el('p','Conversation ended. This step is still waiting.'))});return}p.append(el('p',s.speech));button(p,s.reply,()=>{previewDone.add(previewStage-1);previewStage++;while(previewDone.has(previewStage-1))previewStage++;previewHas=false;simulate()});}
 d.addEventListener('cancel',()=>{if(draft)storeDraft()});
 const launch=el('button','Quests');launch.id='openQuests';launch.onclick=open;(document.querySelector('.palette')||document.querySelector('header')).prepend(launch);
 return {open};
})();
