package com.openrsc.server.constants;

   
                          
     
public enum Spells {
	                                                                                
	                                                                             
	CONFUSE_R,                    
	CHILL_BOLT,                    
	WIND_STRIKE,
	THICK_SKIN,                    
	BURST_OF_STRENGTH,                    
	CONFUSE,
	SHOCK_BOLT,                    
	CAMOFLAUGE,                    
	WATER_STRIKE,
	ENCHANT_LVL1_AMULET,
	ELEMENTAL_BOLT,                    
	EARTH_STRIKE,
	ROCK_SKIN,                    
	WEAKEN,
	FEAR,                    
	FIRE_STRIKE,
	WIND_BOLT_R,                    
	BONES_TO_BREAD,                                                         
	BONES_TO_BANANAS,
	WIND_BOLT,
	CURSE,
	LOW_LEVEL_ALCHEMY,
	WATER_BOLT,
	VARROCK_TELEPORT,
	ENCHANT_LVL2_AMULET,
	EARTH_BOLT,
	LUMBRIDGE_TELEPORT,
	TELEKINETIC_GRAB,
	FIRE_BOLT,
	FALADOR_TELEPORT,
	CRUMBLE_UNDEAD,
	WIND_BLAST,
	SUPERHEAT_ITEM,
	CALL_ANIMAL,                                                                                            
	CAMELOT_TELEPORT,
	WATER_BLAST,
	ENCHANT_LVL3_AMULET,
	IBAN_BLAST,
	RAISE_SKELETON,                                                                                            
	ARDOUGNE_TELEPORT,
	EARTH_BLAST,
	HIGH_LEVEL_ALCHEMY,
	CHARGE_WATER_ORB,
	ENCHANT_LVL4_AMULET,
	WATCHTOWER_TELEPORT,
	FIRE_BLAST,
	CHARGE_EARTH_ORB,
	CLAWS_OF_GUTHIX,
	SARADOMIN_STRIKE,
	FLAMES_OF_ZAMORAK,
	SUMMON_DEMON,                                                                                            
	WIND_WAVE,
	CHARGE_FIRE_ORB,
	WATER_WAVE,
	CHARGE_AIR_ORB,
	VULNERABILITY,
	ENCHANT_LVL5_AMULET,
	EARTH_WAVE,
	ENFEEBLE,
	FIRE_WAVE,
	STUN,
	CHARGE
}
