package com.openrsc.server.net.rsc.enums;

public enum OpcodeIn {
	HEARTBEAT,
	WALK_TO_ENTITY,
	WALK_TO_POINT,
	CONFIRM_LOGOUT,
	LOGOUT,
	BLINK,
	COMBAT_STYLE_CHANGED,
	QUESTION_DIALOG_ANSWER,

	PLAYER_APPEARANCE_CHANGE,
	SOCIAL_ADD_IGNORE,
	SOCIAL_ADD_DELAYED_IGNORE,          
	SOCIAL_ADD_FRIEND,
	SOCIAL_SEND_PRIVATE_MESSAGE,
	SOCIAL_REMOVE_FRIEND,
	SOCIAL_REMOVE_IGNORE,

	DUEL_FIRST_SETTINGS_CHANGED,
	DUEL_FIRST_ACCEPTED,
	DUEL_DECLINED,
	DUEL_OFFER_ITEM,
	DUEL_SECOND_ACCEPTED,

	INTERACT_WITH_BOUNDARY,
	INTERACT_WITH_BOUNDARY2,
	CAST_ON_BOUNDARY,
	USE_WITH_BOUNDARY,

	NPC_TALK_TO,
	NPC_COMMAND,
	NPC_COMMAND2,          
	NPC_ATTACK,
	CAST_ON_NPC,
	NPC_USE_ITEM,

	PLAYER_CAST_PVP,
	PLAYER_USE_ITEM,
	PLAYER_ATTACK,
	PLAYER_DUEL,
	PLAYER_INIT_TRADE_REQUEST,
	PLAYER_FOLLOW,

	CAST_ON_GROUND_ITEM,
	GROUND_ITEM_USE_ITEM,
	GROUND_ITEM_TAKE,

	CAST_ON_INVENTORY_ITEM,
	ITEM_USE_ITEM,
	ITEM_UNEQUIP_FROM_INVENTORY,
	ITEM_EQUIP_FROM_INVENTORY,
	ITEM_UNEQUIP_FROM_EQUIPMENT,          
	ITEM_EQUIP_FROM_BANK,          
	ITEM_REMOVE_TO_BANK,          
	ITEM_COMMAND,
	ITEM_DROP,

	CAST_ON_SELF,
	CAST_ON_LAND,

	OBJECT_COMMAND,
	OBJECT_COMMAND2,
	CAST_ON_SCENERY,
	USE_ITEM_ON_SCENERY,

	SHOP_CLOSE,
	SHOP_BUY,
	SHOP_SELL,

	PLAYER_ACCEPTED_INIT_TRADE_REQUEST,
	PLAYER_DECLINED_TRADE,
	PLAYER_ADDED_ITEMS_TO_TRADE_OFFER,
	PLAYER_ACCEPTED_TRADE,

	PRAYER_ACTIVATED,
	PRAYER_DEACTIVATED,

	GAME_SETTINGS_CHANGED,
	CHAT_MESSAGE,
	COMMAND,
	PRIVACY_SETTINGS_CHANGED,
	REPORT_ABUSE,
	BANK_CLOSE,
	BANK_WITHDRAW,
	BANK_DEPOSIT,

	BANK_DEPOSIT_ALL_FROM_INVENTORY,          
	BANK_DEPOSIT_ALL_FROM_EQUIPMENT,          
	BANK_SAVE_PRESET,          
	BANK_LOAD_PRESET,          
	INTERFACE_OPTIONS,          

	SLEEPWORD_ENTERED,

	SKIP_TUTORIAL,
	ON_BLACK_HOLE,          
	NPC_DEFINITION_REQUEST,          

	LOGIN,
	RELOGIN,             
	REGISTER_ACCOUNT,                            
	FORGOT_PASSWORD,                            
	RECOVERY_ATTEMPT,                            

	CHANGE_RECOVERY_REQUEST,                            
	CHANGE_DETAILS_REQUEST,                            

	CHANGE_PASS,                            
	SET_RECOVERY,                            
	SET_DETAILS,                            

	CANCEL_RECOVERY_REQUEST,                            

	SEND_DEBUG_INFO,                            
	KNOWN_PLAYERS,                            
}
